version: "3.7"

####################################################### EXTENSION FIELDS

## ETCD MAIN SERVICE DEFINITION
x-etcd: &etcd
  image: gcr.io/etcd-development/etcd:v3.3.12
  restart: always
  networks:
    - etcd-net

## ETCD MAIN ENVIRONMENT DEFINITION    
x-etcd-env: &etcd_env 
  ETCD_DATA_DIR: /etcd-data
  ETCD_INITIAL_CLUSTER_TOKEN : etcd-cluster
  ETCD_INITIAL_CLUSTER_STATE : new
  ETCD_LISTEN_CLIENT_URLS    : http://0.0.0.0:2379
  ETCD_LISTEN_PEER_URLS      : http://0.0.0.0:2380
  ETCD_INITIAL_CLUSTER: >
    etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  ETCD_DEBUG  : 1
  ETCDCTL_API : 3

####################################################### SERVICE DEFINITIONS
  
services:

  simple-watch:
    image: solom0n89/jetcd-issue-532:latest
    build:
      context: ./simple-watch
    networks:
      - etcd-net 

  ###################### ETCD STATIC CLUSTER CONFIGURATION
  
  etcd0:                                
    << : *etcd
    environment: 
      << : *etcd_env
      ETCD_INITIAL_ADVERTISE_PEER_URLS : http://etcd0:2380
      ETCD_ADVERTISE_CLIENT_URLS       : http://etcd0:2379
      ETCD_NAME: etcd0
  
  etcd1:                                
    << : *etcd
    environment: 
      << : *etcd_env
      ETCD_INITIAL_ADVERTISE_PEER_URLS : http://etcd1:2380
      ETCD_ADVERTISE_CLIENT_URLS       : http://etcd1:2379
      ETCD_NAME: etcd1
      
  etcd2:                                
    << : *etcd
    environment: 
      << : *etcd_env
      ETCD_INITIAL_ADVERTISE_PEER_URLS : http://etcd2:2380
      ETCD_ADVERTISE_CLIENT_URLS       : http://etcd2:2379
      ETCD_NAME: etcd2

####################################################### NETWORK DEFINITIONS

networks:
  etcd-net:
  
